### ISSUE TITLE
Нихрена не происходит в приложении, если нету папки 110_device_conf

### ISSUE THREAD

**Issue by spy931** [romangolovkou/AQteck_toolMAX#22]
Если запустить приложение без папки 110_device_conf, но не от ображается никакая ошибка, приложение не вілетает но и ничего не происходит.
Ветка -  variant110_china.

Хоть бы какое то сообщение отобразил, мол "Не вижу ниодной доступной конфигурации"

Садись, 2

**Comment by spy931** [comment]
Продолжение. Если папка есть, но внутри нету ниодного файла, то окно откроется, но не отобразит ниодного устройста.
Надо бы написать, что список доступных конфигураций пуст.

**Comment by romangolovkou** [comment]
Виправлено в інщій гілці
